#!/bin/bash

git clone https://github.com/sabre1041/camel-openshift.git $OPENSHIFT_TMP_DIR/camel-openshift

pushd $OPENSHIFT_TMP_DIR/camel-openshift

mvn clean install -DskipTests

rm -rf $OPENSHIFT_TMP_DIR/camel-openshift
